name: dnscrypt-proxy
version: "2.0.24"
summary: A flexible DNS proxy, with support for encrypted DNS protocols
description: |
  A flexible DNS proxy, with support for encrypted DNS protocols.
grade: stable
confinement: classic
base: core18
parts:
  dnscrypt-proxy:
    plugin: go
    source: https://github.com/jedisct1/dnscrypt-proxy.git
    go-importpath: github.com/jedisct1/dnscrypt-proxy
    build-packages:
      - gcc
  example-config-files:
    plugin: dump
    source: .
    organize:
      dnscrypt-proxy/example-dnscrypt-proxy.toml: etc/dnscrypt-proxy.toml
      dnscrypt-proxy/*.txt: etc/
    stage:
      - etc
apps:
  dnscrypt-proxy:
    command: bin/dnscrypt-proxy
    daemon: simple
    restart-condition: on-abnormal
    plugs:
      - home
      - network
      - network-bind
