server_names = ['odohtarget']
listen_addresses = ['127.0.0.1:5300']

[query_log]
file = 'query.log'

[static]
  [static.'odohtarget']
  stamp = 'sdns://BQcAAAAAAAAAF29kb2guY2xvdWRmbGFyZS1kbnMuY29tCi9kbnMtcXVlcnk'