name: Build Optimized Go Binary

permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build (Linux/AMD64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup Go 1.26.1
        uses: actions/setup-go@main
        with:
            go-version-file: 'go.mod'

      - name: Build Optimized Binary
        env:
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64
          GOEXPERIMENT: "greenteagc,jsonv2,nodwarf5,simd,newinliner,runtimefreegc"
          GOGC: "2000"
          GOAMD64: v3
          GODEBUG: "thp=1,netdns=go,gctrace=0,madvdontneed=1,tls13=1,asyncpreemptoff=1"
          GOPRIVATE: ""
          GOPROXY: "https://proxy.golang.org,direct"
        run: |
          go get codeberg.org/miekg/dns@main
          go get github.com/quic-go/quic-go@master
          go get google.golang.org/grpc
          go get github.com/gorilla/websocket@main
          go get github.com/hashicorp/go-immutable-radix/v2@v2
          go get github.com/davecgh/go-spew
          go get github.com/quic-go/qpack@master
          go mod tidy
          go mod vendor
          go build \
            -pgo=default.pgo \
            -mod=mod \
            -trimpath \
            -tags="netgo,osusergo" \
            -ldflags="-s -w -d -funcalign=32 -linkmode=internal -compressdwarf=false" \
            -o dnscrypt-proxy \
            ./dnscrypt-proxy

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: dnscrypt-proxy-linux-amd64
          path: dnscrypt-proxy
          if-no-files-found: error
          retention-days: 5
